# Save And Load Trained Model with Pickle and joblib

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [20]:
#load necessary libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

In [21]:
#read the dataset
df = pd.read_csv("datasets/homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [54]:
#create a linear regression model
model = linear_model.LinearRegression()
#fit the model to the data
x=df[['area']]
y=df.price
model.fit(x,y)
print("Model fitted successfully")

Model fitted successfully


In [39]:
model.coef_

array([135.78767123])

In [40]:
model.intercept_

180616.43835616432

In [41]:
model.predict([[5000]])

array([859554.79452055])

### Save Model To a File Using Python Pickle

In [42]:
import pickle

In [43]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

### Load Saved Model

In [44]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [45]:
mp.coef_

array([135.78767123])

In [46]:
mp.intercept_

180616.43835616432

In [47]:
mp.predict([[5000]])

array([859554.79452055])

### Save Trained Model Using joblib

In [48]:
import joblib

In [49]:
joblib.dump(model, 'model_joblib')

['model_joblib']

### Load Saved Model

In [50]:
mj = joblib.load('model_joblib')

In [51]:
mj.coef_

array([135.78767123])

In [52]:
mj.intercept_

180616.43835616432

In [53]:
mj.predict([[5000]])

array([859554.79452055])